server:
  port: 9400

#spring:
#  datasource:
#    url: jdbc:mariadb://188.120.229.168:3306/LifeRussia
#    username: launcherIvan
#    password: 2281337
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/liverussia_test
    username: root
    password: 122021

#  jpa:
#    hibernate:
#      ddl-auto: update
#    generate-ddl: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

api:
  prefix: /api/v1
  endpoints:
    roleAdmin:
      /api/v1/admin/**
    roleAndroidUser:
      /api/v1/android/user/**
    permitAll:
      /api/v1/auth/android/login,
      /api/v1/auth/admin/login,
      /api/v1/auth/token,
      /api/v1/auth/android/refresh,
      /api/v1/auth/admin/refresh,
      /api/v1/auth/registration,
      /api/v1/android/setting/**


vue-client:
  url: http://localhost:8080

google:
  recaptcha:
    verification:
      endpoint: https://www.google.com/recaptcha/api/siteverify
      secret: 6Ldt5oAhAAAAAInVjY62F8MfKjnFWkx7aG19B-Mo

jwt:
  secret:
    access:
      token: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
      duration:
        minutes: 5
    refresh:
      token: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==
      duration:
        days: 30

android:
  roulette:
    countElementsInOneSpin: 104
    spinDurationInMillis: 8000
    spinCost: 50


upload:
  path: /Users/ivanlikhvatov/SAMP/liverussia-launcher-server/uploads/