server:
  port: 9400

spring:
  datasource:
    url: jdbc:mariadb://188.120.229.168:3306/LifeRussia
    username: launcherIvan
    password: 2281337
#  jpa:
#    generate-ddl: true

api:
  prefix: /api/v1
  endpoints:
    roleAdmin:
      /api/v1/admin/**
    roleAndroidUser:
      /api/v1/android/**
    permitAll:
      /api/v1/auth/login,
      /api/v1/auth/token,
      /api/v1/auth/refresh,
      /api/v1/auth/registration,
      /api/v1/test/helloworld,
      /api/v1/test/getFromDb


vue-client:
  url: http://localhost:8080
  confirm-register-path: /registration/activate
  login: /login

google:
  recaptcha:
    verification:
      endpoint: https://www.google.com/recaptcha/api/siteverify
      secret: 6Ldt5oAhAAAAAInVjY62F8MfKjnFWkx7aG19B-Mo

jwt:
  secret:
    access:
      token: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
      duration:
        minutes: 5
    refresh:
      token: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==
      duration:
        days: 30


upload:
  path: /Users/ivanlikhvatov/AllProjects/JavaProjects/SpringRestProjects/disease-control-system/uploads/